In [1]:
import pandas as pd
import numpy as np

from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [2]:
df = pd.read_csv("./compras.csv", header=None)
df.sample(10)

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
3945,whipped/sour cream,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6977,whole milk,dessert,yogurt,white bread,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4419,beef,citrus fruit,tropical fruit,pip fruit,berries,root vegetables,other vegetables,whole milk,dessert,sliced cheese,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5337,hamburger meat,berries,other vegetables,UHT-milk,hard cheese,processed cheese,canned vegetables,soda,waffles,specialty bar,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4496,pickled vegetables,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7886,sausage,packaged fruit/vegetables,UHT-milk,pastry,soups,bottled water,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3403,whole milk,bottled water,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1278,frankfurter,ham,root vegetables,onions,whole milk,yogurt,rolls/buns,white bread,brown bread,margarine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
992,cream cheese,margarine,tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2412,sausage,hamburger meat,tropical fruit,cream cheese,fruit/vegetable juice,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.replace(np.nan, 0, inplace = True)
df.sample(10)

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
3128,beef,chocolate,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5612,frankfurter,whole milk,cream cheese,specialty chocolate,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2735,rolls/buns,canned fruit,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4970,canned beer,newspapers,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2868,whole milk,dessert,yogurt,sliced cheese,rolls/buns,soda,seasonal products,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2699,ham,pork,other vegetables,whole milk,frozen vegetables,rolls/buns,rum,0,0,0,...,0,0,0,0,0,0,0,0,0,0
215,beverages,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3482,canned beer,shopping bags,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4154,frankfurter,tropical fruit,root vegetables,rolls/buns,mustard,canned fish,misc. beverages,bottled beer,shopping bags,0,...,0,0,0,0,0,0,0,0,0,0
8967,tropical fruit,salt,canned fish,bottled water,bottled beer,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
transacoes = []

for index, row in df.iterrows():
    transacao_unica = row.values.tolist()
    transacao_unica = [item for item in transacao_unica if item != 0]
    transacoes.append(transacao_unica)

print(transacao_unica[0:10])

['chicken', 'tropical fruit', 'other vegetables', 'vinegar', 'shopping bags']

In [5]:
enconder = TransactionEncoder()
matriz = enconder.fit(transacoes).transform(transacoes)

df_transacoes = pd.DataFrame(matriz, columns=enconder.columns_)
df_transacoes.head()

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [6]:
itens_frequentes = apriori(df_transacoes, min_support = 0.01, use_colnames = True)
itens_frequentes.sort_values(by=['support'], ascending = False).head(10)

     support                       itemsets
86  0.255516        frozenset({whole milk})
55  0.193493  frozenset({other vegetables})
66  0.183935        frozenset({rolls/buns})
75  0.174377              frozenset({soda})
87  0.139502            frozenset({yogurt})
6   0.110524     frozenset({bottled water})
67  0.108998   frozenset({root vegetables})
81  0.104931    frozenset({tropical fruit})
73  0.098526     frozenset({shopping bags})
70  0.093950           frozenset({sausage})

In [7]:
regras = association_rules(itens_frequentes, metric="confidence", min_threshold=0.3)
regras.sort_values(by=['lift'], ascending = False).drop(['antecedent support', 'consequent support', 'leverage', 'conviction'], axis=1)

,antecedents,consequents,support,confidence,lift,representativity,zhangs_metric,jaccard,certainty,kulczynski
73,"frozenset({other vegetables, citrus fruit})",frozenset({root vegetables}),0.010371,0.359155,3.295045,1.0,0.717225,0.081340,0.280759,0.227152
95,"frozenset({other vegetables, tropical fruit})",frozenset({root vegetables}),0.012303,0.342776,3.144780,1.0,0.707403,0.092791,0.262376,0.227825
1,frozenset({beef}),frozenset({root vegetables}),0.017387,0.331395,3.040367,1.0,0.708251,0.120677,0.249603,0.245455
74,"frozenset({root vegetables, citrus fruit})",frozenset({other vegetables}),0.010371,0.586207,3.029608,1.0,0.681990,0.051646,0.486932,0.319903
96,"frozenset({root vegetables, tropical fruit})",frozenset({other vegetables}),0.012303,0.584541,3.020999,1.0,0.683367,0.060835,0.484867,0.324062
...,...,...,...,...,...,...,...,...,...,...
65,frozenset({waffles}),frozenset({whole milk}),0.012710,0.330688,1.294196,1.0,0.236406,0.045192,0.100972,0.190215
17,frozenset({coffee}),frozenset({whole milk}),0.018709,0.322242,1.261141,1.0,0.219830,0.063448,0.089627,0.197730
61,frozenset({sausage}),frozenset({whole milk}),0.029893,0.318182,1.245252,1.0,0.217372,0.093541,0.084173,0.217587
6,frozenset({bottled water}),frozenset({whole milk}),0.034367,0.310948,1.216940,1.0,0.200417,0.103617,0.074456,0.222724
59,frozenset({rolls/buns}),frozenset({whole milk}),0.056634,0.307905,1.205032,1.0,0.208496,0.147942,0.070369,0.264776